#!/bin/sh

# PHP-FPM [www] pool configuration
envsubst < /etc/php/fpm/pool.d/www.conf.tmpl        > /etc/php/${PHP_VERSION}/fpm/pool.d/www.conf
# Opcache Module configuration
envsubst < /etc/php/mods-available/opcache.ini.tmpl > /etc/php/${PHP_VERSION}/mods-available/opcache.ini
# PHP configuration (ie. memory_limit, upload_max_size)
envsubst < /etc/php/mods-available/config.ini.tmpl  > /etc/php/${PHP_VERSION}/fpm/conf.d/99-config.ini

# Allow running commands by CMD
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
