#!/bin/bash

SCRIPT_NAME=05-configure-xdebug
XDEBUG_CONFIG_FILE=/etc/php/${PHP_VERSION}/mods-available/xdebug.ini

if [ ${XDEBUG_ENABLE} == '1' ] || [ ${XDEBUG_ENABLE} == 'On' ]
then 
	{ \
		echo 'zend_extension=xdebug.so'; \
		echo "xdebug.mode=${XDEBUG_MODE}"; \
	} > ${XDEBUG_CONFIG_FILE}
    echo "${SCRIPT_NAME}: XDEBUG configured & enabled"
else
    echo "${SCRIPT_NAME}: XDEBUG disabled"
fi;
