#!/bin/sh

FPM_POOL_DIR="/etc/php/${PHP_VERSION}/fpm/pool.d"
# compile only if php-fpm installed
if [ -d $FPM_POOL_DIR ]; then && envsubst < /etc/php/fpm/pool.d/www.conf.tmpl > ${FPM_POOL_DIR}/www.conf; fi;
