#!/bin/sh

IMAGE_NAME=${DOCKERHUB_USERNAME}/php
IMAGE_TAG_SUFFIX=-fpm
IMAGE_TAG=${PHP_VERSION}${IMAGE_TAG_SUFFIX}

docker load --input ${IMAGE_TAG}.tar

IMAGE_VERSION_TAG=$(docker run ${IMAGE_NAME}:${IMAGE_TAG} -v | grep -Eo -m 1 '[0-9]+\.[0-9]+\.[0-9]+')${IMAGE_TAG_SUFFIX}
IMAGE_DATE_TAG=${IMAGE_VERSION_TAG}-$(date +"%Y%m%d")

docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${IMAGE_DATE_TAG}
docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${IMAGE_VERSION_TAG}

docker login -u=${DOCKERHUB_USERNAME} -p=${DOCKERHUB_PASSWORD}

docker push ${IMAGE_NAME}:${IMAGE_TAG}
docker push ${IMAGE_NAME}:${IMAGE_DATE_TAG}
docker push ${IMAGE_NAME}:${IMAGE_VERSION_TAG}