name: "Build & push stable Docker images"

on:
  schedule:
    - cron: "30 4 * * *"
  push:
    tags:
      - "v*.*.*"

jobs:

  # php74-fpm-image-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: Build Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       push: true
  #       platforms: linux/amd64,linux/arm64
  #       tags: milejko/php-fpm:7.4,milejko/php-fpm:7.4-latest
  #       build-args: PHP_VERSION=7.4

  # php80-fpm-image-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: Build Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       push: true
  #       platforms: linux/amd64,linux/arm64
  #       tags: milejko/php-fpm:8.0,milejko/php-fpm:8.0-latest
  #       build-args: PHP_VERSION=8.0

  # php81-fpm-image-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: Build Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       push: true
  #       platforms: linux/amd64,linux/arm64
  #       tags: milejko/php-fpm:8.1,milejko/php-fpm:8.0-latest
  #       build-args: PHP_VERSION=8.1

  php82-fpm-image-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: milejko/php-fpm
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: milejko/php-fpm:8.2,milejko/php-fpm:8.2-latest,milejko/php-fpm:latest,${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: PHP_VERSION=8.2