name: "PHP Docker NE images delivery"

on:
  schedule:
    # twice per month
    - cron: "15 5 1,14 * *"
  push:
    tags:
      - "v*.*.*"

jobs:

  Deploy:
    name: "Image deployment"
    strategy:
      matrix:
        base-image: ['jammy', 'bookworm']
        php-version: ['7.4', '8.0', '8.1', '8.2']
        target: ['fpm']
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Docker Image
      uses: docker/build-push-action@v5
      with:
        push: false
        file: ./${{ matrix.base-image }}/Dockerfile
        context: ./${{ matrix.base-image }}/
        target: ${{ matrix.target }}
        tags: testing
        build-args: PHP_VERSION=${{ matrix.php-version }}
    - 
      name: Dump installed PHP version
      run: echo "PHP_REAL_VERSION=$(docker run testing -v | grep -Eo -m 1 '[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV
    - 
      name: Check PHP version
      run: echo "${{ env.PHP_REAL_VERSION }}" | grep "${{ matrix.php-version }}"
    - 
      name: Perform image tests
      run: IMAGE_TAG=testing ./.github/workflows/test-image.sh
    - 
      name: "Check FPM"
      if: ${{ 'fpm' == matrix.target }}
      run: |
        docker run testing find /usr/bin/php-fpm
        docker run testing /usr/bin/php-fpm --daemonize
    - 
      name: "Check CLI"
      if: ${{ 'cli' == matrix.target }}
      run: docker run testing | grep "Interactive"
    - 
      name: Set up QEMU (multiplatform)
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx (multiplatform)
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.NE_DOCKERHUB_USERNAME }}
        password: ${{ secrets.NE_DOCKERHUB_TOKEN }}
    - 
      name: Prepare image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.NE_DOCKERHUB_USERNAME }}/php
        # sample tag output: 8.2-cli, 8.2, latest, cli, 8.2.11-cli, 8.2.11-cli-20230712, 8.2.11
        tags: |
          type=raw,value=${{ matrix.php-version }}-${{ matrix.target }},enable=${{ 'bookworm' == matrix.base-image }}
          type=raw,value=${{ matrix.php-version }},enable=${{ 'cli' == matrix.target && 'bookworm' == matrix.base-image }}
          type=raw,value=latest,enable=${{ '8.2' == matrix.php-version && 'cli' == matrix.target && 'bookworm' == matrix.base-image }}
          type=raw,value=${{ matrix.target }},enable=${{ '8.2' == matrix.php-version && 'bookworm' == matrix.base-image }}
          type=raw,value=${{ env.PHP_REAL_VERSION }}-${{ matrix.target }},enable=${{ 'bookworm' == matrix.base-image }}
          type=raw,value=${{ env.PHP_REAL_VERSION }}-${{ matrix.target }}-{{ date 'YYYYMMDD' }},enable=${{ 'bookworm' == matrix.base-image }}
          type=raw,value=${{ env.PHP_REAL_VERSION }},enable=${{ 'cli' == matrix.target && 'bookworm' == matrix.base-image }}

          type=raw,value=${{ matrix.php-version }}-${{ matrix.target }}-${{ matrix.base-image }}
          type=raw,value=${{ matrix.php-version }}-${{ matrix.base-image }},enable=${{ 'cli' == matrix.target }}
          type=raw,value=${{ matrix.target }}-${{ matrix.base-image }},enable=${{ '8.2' == matrix.php-version }}
          type=raw,value=${{ env.PHP_REAL_VERSION }}-${{ matrix.target }}-${{ matrix.base-image }}
          type=raw,value=${{ env.PHP_REAL_VERSION }}-${{ matrix.target }}-${{ matrix.base-image }}-{{date 'YYYYMMDD'}}
          type=raw,value=${{ env.PHP_REAL_VERSION }}-${{ matrix.base-image }},enable=${{ 'cli' == matrix.target }}

    - 
      name: Build & push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./${{ matrix.base-image }}/Dockerfile
        context: ./${{ matrix.base-image }}/
        platforms: linux/amd64,linux/arm64/v8
        target: ${{ matrix.target }}
        tags: ${{ steps.meta.outputs.tags }},
        labels: ${{ steps.meta.outputs.labels }},
        build-args: PHP_VERSION=${{ matrix.php-version }}
