name: "PHP Bookworm CI"

on:
  pull_request:
  push:

jobs:
  php82-cli-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-cli
        tags: php-cli-testing
        build-args: PHP_VERSION=8.2
    - 
      name: Check CLI version
      run: docker run php-cli-testing -v
    - 
      name: Check running PHP command
      run: docker run php-cli-testing -r 'phpinfo();'
    - 
      name: Check interactive shell
      run: docker run php-cli-testing | grep "blob"

  php82-fpm-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Doker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-fpm
        tags: php-fpm-testing
        build-args: PHP_VERSION=8.2
    - 
      name: Check FPM binary
      run: docker run --entrypoint="" php-fpm-testing find /usr/sbin/php-fpm8.2
    - 
      name: Check CLI version
      run: docker run --entrypoint="" php-fpm-testing php -v

  php81-cli-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-cli
        tags: php-cli-testing
        build-args: PHP_VERSION=8.1
    - 
      name: Check CLI version
      run: docker run php-cli-testing -v
    - 
      name: Check running PHP command
      run: docker run php-cli-testing -r 'phpinfo();'
    - 
      name: Check interactive shell
      run: docker run php-cli-testing

  php81-fpm-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Doker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-fpm
        tags: php-fpm-testing
        build-args: PHP_VERSION=8.1
    - 
      name: Check FPM binary
      run: docker run --entrypoint="" php-fpm-testing find /usr/sbin/php-fpm8.1
    - 
      name: Check CLI version
      run: docker run --entrypoint="" php-fpm-testing php -v

  php80-cli-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-cli
        tags: php-cli-testing
        build-args: PHP_VERSION=8.0
    - 
      name: Check CLI version
      run: docker run php-cli-testing -v
    - 
      name: Check running PHP command
      run: docker run php-cli-testing -r 'phpinfo();'
    - 
      name: Check interactive shell
      run: docker run php-cli-testing

  php80-fpm-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Doker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-fpm
        tags: php-fpm-testing
        build-args: PHP_VERSION=8.0
    - 
      name: Check FPM binary
      run: docker run --entrypoint="" php-fpm-testing find /usr/sbin/php-fpm8.0
    - 
      name: Check CLI version
      run: docker run --entrypoint="" php-fpm-testing php -v

  php74-cli-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-cli
        tags: php-cli-testing
        build-args: PHP_VERSION=7.4
    - 
      name: Check CLI version
      run: docker run php-cli-testing -v
    - 
      name: Check running PHP command
      run: docker run php-cli-testing -r 'phpinfo();'
    - 
      name: Check interactive shell
      run: docker run php-cli-testing

  php74-fpm-image-test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Doker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-fpm
        tags: php-fpm-testing
        build-args: PHP_VERSION=7.4
    - 
      name: Check FPM binary
      run: docker run --entrypoint="" php-fpm-testing find /usr/sbin/php-fpm7.4
    - 
      name: Check CLI version
      run: docker run --entrypoint="" php-fpm-testing php -v

