name: "Build & push stable PHP 7.3 Docker images"

on:
  # only after repository update
  push:
    tags:
      - "v*.*.*"

jobs:
  php-fpm-image-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    -
      name: Calculate daily tag name
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: milejko/php-fpm
        tags: |
          type=raw,value=7.3-{{date 'YYYYMMDD'}}
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: milejko/php-fpm:7.3,milejko/php-fpm:7.3-latest,milejko/php-fpm:latest,${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: PHP_VERSION=7.3