name: "Build & push stable PHP-CLI PHP 8.2 Docker images"

on:
  schedule:
    # once per week
    - cron: "30 4 * * 0"
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  php-images-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Calculating image meta - tags & labels
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: milejko/php
        tags: |
          type=raw,value=8.2-cli-{{date 'YYYYMMDD'}}
          type=raw,value=8.2-cli
          type=raw,value=cli-latest
          type=raw,value=latest
