name: "Preview PHP Docker Images delivery"

on:
  schedule:
    # once per week
    - cron: "20 4 * * 0"
  push:
    tags:
      - "v*.*.*"

jobs:
  php83-cli-image-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Preparing image meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: milejko/php
        tags: |
          type=raw,value=8.3-cli-{{date 'YYYYMMDD'}}
          type=raw,value=8.3-cli-preview
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        target: php-cli
        tags: ${{ steps.meta.outputs.tags }},
        labels: ${{ steps.meta.outputs.labels }},
        build-args: PHP_VERSION=8.3

  php83-fpm-image-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Calculating image meta - tags & labels
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: milejko/php
        tags: |
          type=raw,value=8.3-fpm-preview-{{date 'YYYYMMDD'}}
          type=raw,value=8.3-fpm-preview
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        target: php-fpm
        tags: ${{ steps.meta.outputs.tags }},
        labels: ${{ steps.meta.outputs.labels }},
        build-args: PHP_VERSION=8.3
