name: "Security Scan"

on:
  schedule:
    # once per week
    - cron: "45 6 * * 1"
  pull_request:

jobs:
  Security:
    name: "Scan"
    strategy:
      #only supported versions (8.1, 8.2) targets - Apache and FPM (as FPM is based on CLI)
      matrix:
        base-image: ['jammy', 'bookworm', 'alpine']
        php-version: ['8.2', '8.1']
        target: ['fpm', 'apache']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        file: ./${{ matrix.base-image }}/Dockerfile
        context: ./${{ matrix.base-image }}/
        target: ${{ matrix.target }}
        tags: testing
        build-args: PHP_VERSION=${{ matrix.php-version }}
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=./${{ matrix.base-image }}/Dockerfile --severity-threshold=high
        image: testing
