name: "Docker image security scan"

on:
  schedule:
    # once per day
    - cron: "45 6 * * *"

jobs:
  php-security-check:
    strategy:
      matrix:
        #only supported versions
        php-version: ['8.3', '8.2', '8.1']
        #only fpm
        variant: ['fpm']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: php-${{ matrix.variant }}
        tags: testing
        build-args: PHP_VERSION=${{ matrix.php-version }}
    -
      name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=Dockerfile --severity-threshold=high
        image: testing
